apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  labels:
    app: admin-dashboard
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 4000
    protocol: TCP
    name: admin
  type: NodePort
  selector:
    app: admin-dashboard
