apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-dashboard
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin-dashboard
    spec:
      #hostNetwork: true
      nodeSelector:
        platform: nuc
      containers:
      - name: admin-dashboard
        image: localhost:30400/admin-portal
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
        command: ["/usr/bin/python", "run.py"]
