apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      #hostNetwork: true
      nodeSelector:
        platform: nuc
      containers:
      - name: long-task
        image: 192.168.2.117:5000/celery-worker
        imagePullPolicy: Always
        #command: ["/bin/sh", "-c", "tail -f /dev/null"]
        command: ["/bin/sh", "-c"]
        args: ["celery amqp queue.delete iot_queue_2 -b amqp://admin:admin@$RABBIT_SERVICE_SERVICE_HOST:$RABBIT_SERVICE_PORT_5672_TCP_PORT && python CeleryTask/tasks.py && celery -A CeleryTask.celeryapp worker -l info -c 1 -Q iot_queue_2"]
      - name: periodic-task
        image: 192.168.2.117:5000/celery-worker
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["celery -A CeleryTask.celeryapp worker -l info -c 1 -Q celery -B"]
