apiVersion: v1
kind: Service
metadata:
  name: home-portal
  labels:
    app: home-dashboard
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 3000
      protocol: TCP
      name: home
  selector:
      app: home-dashboard
