apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      #hostNetwork: true
      nodeSelector:
        platform: nuc
      containers:
      - name: master
        image: 192.168.1.102:5000/mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "intel123"
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-root-pass
          #    key: mysql-root-pass.secret
        - name: MYSQL_REPL_PASSWORD
          value: "intel123"
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-root-pass
          #    key: mysql-root-pass.secret
        - name: ROLE
          value: "Master"
