apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        #app: taskQueue
        app: rabbitmq
    spec:
      #hostNetwork: true
      nodeSelector:
        platform: nuc
      containers:
      - image: localhost:30400/rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
